---
title: "ACT Analysis"
author: "Steven Macapagal"
date: "6/6/2022"
output: html_document
---

## Notebook setup

* Filename: 01-act-analysis.Rmd
* Path: ./src/01-act-analysis.Rmd
* Author: Steven Macapagal
* Date created: 2022-06-06
* Date modified: 2022-06-06
* Purpose: This notebook preps and conducts analysis ACT data for Question 3.
* Inputs: df_act
* Outputs: 
* Notes:

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## ACT data at a glance

```{r}
glimpse(df_act)
```

## ACT data summaries

```{r}
df_act %>%
  group_by(GradeLevelID) %>%
  summarize(n = n(),
            MeanScience = mean(Science, na.rm = TRUE))
```


```{r}
df_act_attendees %>%
  filter(GradeLevelID %in% c(10, 11, 12)) %>%
  group_by(StudentNumber) %>%
  filter(Science == max(Science, na.rm = TRUE)) %>%
  ungroup() %>%
  group_by(GradeLevelID) %>%
  summarize(n = n(),
            MeanScience = mean(Science, na.rm = TRUE))
```


```{r}
df_act_survey_takers %>%
  filter(GradeLevelID %in% c(10, 11, 12)) %>%
  group_by(StudentNumber) %>%
  filter(Science == max(Science, na.rm = TRUE)) %>%
  ungroup() %>%
  group_by(GradeLevelID) %>%
  summarize(n = n(),
            MeanScience = mean(Science, na.rm = TRUE))
```


```{r}
df_act_survey_takers %>%
  filter(GradeLevelID %in% c(10, 11, 12)) %>%
  group_by(StudentNumber) %>%
  filter(Science == max(Science, na.rm = TRUE)) %>%
  ungroup() %>%
  group_by(GradeLevelID,
           CRDoseGroup) %>%
  summarize(n = n(),
            MeanScience = mean(Science, na.rm = TRUE))
```

