---
title: "GPA analysis"
author: "Steven Macapagal"
date: "6/14/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Notebook setup

* Filename: 04-gpa-analysis.Rmd
* Path: ./src/04-gpa-analysis.Rmd
* Author: Steven Macapagal
* Date created: 2022-06-14
* Date modified: 2022-06-14
* Purpose: This notebook preps and conducts analysis for GPA data for Question 3.
* Inputs: df_gpa_all_attendees, df_gpa_survey_takers
* Outputs: 
* Notes:

## Analysis of all GPAs

```{r}
raw_gpa %>%
  group_by(GradeLevelID) %>%
  summarize(n = n(),
            MeanGPA = mean(CumulativeGPA, na.rm=TRUE))
```

## Analysis of Camp Rio attendees

```{r}
df_gpa_attendees %>%
  group_by(GradeLevelID) %>%
  summarize(n = n(),
            MeanGPA = mean(CumulativeGPA, na.rm=TRUE))
```

```{r}
df_gpa_survey_takers %>%
  filter(CumulativeGPA != 0) %>%
  group_by(GradeLevelID.x) %>%
  summarize(n = n(),
            MeanGPA = mean(CumulativeGPA, na.rm=TRUE))
```

```{r}
df_gpa_survey_takers %>%
  filter(CumulativeGPA != 0) %>%
  group_by(GradeLevelID.x,
           CRDoseGroup) %>%
  summarize(n = n(),
            MeanGPA = mean(CumulativeGPA, na.rm=TRUE))
```



# Tests on dosage